### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by thekrugers** [Dionach/NtdsAudit#15]
When using the -p parameter, the following exception crash happens up at 32%:

Unhandled Exception:\System.NullReferenceException: Object reference not set to
an instance of an object.
   at NtdsAudit.SystemHive.LoadSystemKeyFromHive(String systemHivePath)
   at NtdsAudit.NtdsAudit.DecryptSecretData(String systemKeyPath, Boolean includeHistoryHashes)
   at NtdsAudit.NtdsAudit..ctor(String ntdsPath, Boolean dumphashes, Boolean includeHistoryHashes, String systemHivePath, String wordlistPath)
   at NtdsAudit.Program.<>c__DisplayClass2_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at NtdsAudit.Program.Main(String[] args)

Happens in version 2.0.5 and 2.0.6

**Comment by mgh42** [comment]
Issue also exists in 2.0.4 and 2.0.7.
