### ISSUE TITLE
Unhandled Exception error on DateTime field.

### ISSUE THREAD

**Issue by arielsepulveda** [dionach/NtdsAudit#17]
Hi, I am getting an error when executing this on some domains:
![Error_NTDSAudit_exception](https://user-images.githubusercontent.com/20051003/103528296-fe5b2300-4e83-11eb-9f33-1923437bba40.png)

I have tested and is not related to .NET so far, looks more related to an unexpected value on a "DateTime" field.

Any idea on how to avoid this? and/or fix the app to sanitize this fields?

Here is another very similar error in text from another domain:
`Unhandled Exception: System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: value
   at System.DateTime.AddTicks(Int64 value)
   at NtdsAudit.NtdsAudit.GetAccountExpiresDateTimeFromByteArray(Byte[] value)
   at NtdsAudit.NtdsAudit.CalculateUserInfo()
   at NtdsAudit.NtdsAudit..ctor(String ntdsPath, Boolean dumphashes, Boolean includeHistoryHashes, String systemHivePath, String wordlistPath, String ouFilterFilePath)
   at NtdsAudit.Program.<>c__DisplayClass2_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at NtdsAudit.Program.Main(String[] args)`

**Comment by arielsepulveda** [comment]
Btw, this error was found on servers with .NET v4.7.03062  and v4.8.03761 ... (and I have others with .NET v4.7.03062 that works) ... so I assume this could be due to an unexpected or not correctly sanitised value from the AD export.
One thing to mention, is that 1 month ago, this was working on the same domains, and it takes some time to give the error (so it may be processing users alreay) until it may found some user with the unexpected value and then gives the exception.

**Comment by ph1ll** [comment]
I believe this is caused by #18, which will have a fix shortly
