### ISSUE TITLE
Handling large files

### ISSUE THREAD

**Issue by mp-dn** [Dionach/NtdsAudit#5]
When running NtdsAudit against a 5 GB ntds.dit file, the following error was thrown after processing ~30% of the file:

```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NtdsAudit.NTCrypto.DecryptSecret(Dictionary`2 pekList, Byte[] encryptedBlob)
   at NtdsAudit.NTCrypto.DecryptHashes(Dictionary`2 pekList, Byte[] encryptedHashBlob, UInt32 rid)
   at NtdsAudit.NtdsAudit.DecryptSecretData(String systemKeyPath, Boolean includeHistoryHashes)
   at NtdsAudit.NtdsAudit..ctor(String ntdsPath, Boolean dumphashes, Boolean includeHistoryHashes, String systemHivePath, String wordlistPath)
   at NtdsAudit.Program.<>c__DisplayClass2_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at NtdsAudit.Program.Main(String[] args)
```

**Comment by ph1ll** [comment]
I have added additional error handling to detail any accounts that cant be decrypted, and to continue with the rest of the audit. 

Unfortunately I cant debug further without an NTDS file to test.
