### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by dnpentest** [Dionach/NtdsAudit#8]
I'm not sure if the error message is accurate or a symptom of something else:

C:\Tools>NtdsAudit.exe "C:\Users\[snip]\Desktop\2018-03-22\active directory\Active Directory\ntds.dit" --system "c:\Users\[snip]\Desktop\2018-03-22\active directory\registry\SYSTEM" --pwdump "c:\users\[snip]\Desktop\2018-03-22\active directory\"

The base date used for statistics is 22/03/2018 14:49:31

Account stats for: [snip]
  Disabled users _____________________________________________________  6176 of 14710 (42%)
  Expired users ______________________________________________________    38 of 14710 (0%)
  Active users unused in 1 year ______________________________________  1263 of  8496 (15%)
  Active users unused in 90 days _____________________________________  2264 of  8496 (27%)
  Active users which do not require a password _______________________   131 of  8496 (2%)
  Active users with non-expiring passwords ___________________________  8016 of  8496 (94%)
  Active users with password unchanged in 1 year _____________________  1445 of  8496 (17%)
  Active users with password unchanged in 90 days ____________________  2556 of  8496 (30%)
  Active users with Administrator rights _____________________________    57 of  8496 (1%)
  Active users with Domain Admin rights ______________________________    38 of  8496 (0%)
  Active users with Enterprise Admin rights __________________________     2 of  8496 (0%)

  Disabled computer accounts _________________________________________   188 of  6361 (3%)

WARNING:
The NTDS file contains user accounts with passwords stored using reversible encryption. Use the --dump-reversible option to output these users and passwords.

Password stats for: nwlh.internal
  Active users using LM hashing ______________________________________  4021 of  8496 (47%)
  Active users with duplicate passwords ______________________________   978 of  8496 (12%)
  Active users with password stored using reversible encryption ______     1 of  8496 (0%)

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at NtdsAudit.Program.WritePwDumpFile(String pwdumpPath, NtdsAudit ntdsAudit, DateTime baseDateTime, Boolean includeHistoryHashes, Boolean wordlistInUse, String dumpReversiblePath)
   at NtdsAudit.Program.<>c__DisplayClass2_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at NtdsAudit.Program.Main(String[] args)

**Comment by dnpentest** [comment]
Sorry it's late and I skimread just the second part of this as being a directory path:
"--pwdump <file>      The path to output hashes in pwdump format"

The cause of the error is that --pwdump should have been passed a file, not a directory

A tweak could be to catch the error and give a error message like "sorry, you've not supplied a file in the --pwdump value"
